# Generated by Django 5.2.5 on 2025-08-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField()),
                ('value', models.IntegerField()),
                ('date', models.DateField()),
                ('source', models.CharField(max_length=100)),
                ('borrowed', models.BooleanField()),
            ],
        ),
    ]
